# Generated by Django 4.2.23 on 2025-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
