# Generated by Django 4.2.23 on 2025-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='book_name')),
                ('description', models.TextField(verbose_name='book_description')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=1)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
